version: "3.7"

services:
  backend:
    build:
      context: ./Backend
    networks:
      - app-network
    depends_on:
      - database
    hostname: backend

  database:
    build:
      context: ./BD_Postgres
    networks:
      - app-network
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    hostname: myapp

  httpd:
    build:
      context: ./ServeurApache
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    hostname: myhttpserver
  
  front:
    build:
      context: ./devops-front
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    hostname: myhttpserver

networks:
  app-network:

volumes:
  data-postgres: