# On choisis la version de docker-compose
version: "3.7"

# On liste les dockers/"Service" a lancer
services:
  
  # Le nom du service
  backend:
    # L'image a récupérer sur docker hub avec la version
    image: quentinles/backend:latest

    # L'ajouter au network "app-network"
    networks:
      - app-network
    depends_on:
      - database
    # On ajouter les variables d'environement
    environment:
      url: jdbc:postgresql://database:5432/db
      user: usr
      password: pwd

  database:
    image: quentinles/myapp:latest
    networks:
      - app-network
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

  httpd:
    image: quentinles/myhttpserver:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  front:
    image: quentinles/devopsfront:latest
    networks:
      - app-network

# On crée le network pour permettre la communication entre les services
networks:
  app-network:

# On ajoute le volume pour que la database enregistre les données
volumes:
  data-postgres: