- name: Create container "backend"
  community.docker.docker_container:
    name: backend
    image: quentinles/backend:latest
    networks:
      - name: app-network
    env:
      url: jdbc:postgresql://database:5432/db
      user: "{{ db_usr }}"
      password: "{{ db_pwd }}"
