- name: Create container "database"
  community.docker.docker_container:
    name: database
    image: quentinles/myapp:latest
    networks:
      - name: app-network
    volumes:
      - data-postgres:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
