- name: Create container "database"
  community.docker.docker_container:
    name: database
    image: quentinles/myapp:latest
    networks:
      - name: app-network
    volumes:
      - data-postgres:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_pwd }}"
