name: CI devops 2023 - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  # Job sans dépendances
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build and deploy
        run: echo "Trigger build and deploy"
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUBNAME }} -p ${{ secrets.DOCKERHUBSECRET }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./Backend
          tags:  ${{ secrets.DOCKERHUBNAME }}/backend:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./BD_Postgres
          tags:  ${{ secrets.DOCKERHUBNAME }}/myapp:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./ServeurApache
          tags:  ${{ secrets.DOCKERHUBNAME }}/myhttpserver:latest
          push: true
