name: CI devops 2023 - Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI devops 2023 - Test Backend"]
    branches: [main]
    types:
        - completed 

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUBNAME }} -p ${{ secrets.DOCKERHUBSECRET }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./Backend
          tags:  ${{ secrets.DOCKERHUBNAME }}/backend:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./BD_Postgres
          tags:  ${{ secrets.DOCKERHUBNAME }}/myapp:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./ServeurApache
          tags:  ${{ secrets.DOCKERHUBNAME }}/myhttpserver:latest
          push: true

      - name: Build and push front image
        uses: docker/build-push-action@v3
        with:
          context: ./devops-front
          tags:  ${{ secrets.DOCKERHUBNAME }}/devopsfront:latest
          push: true