name: CI devops 2023 - Deploy Docker Images

# on:
#   workflow_run:
#     workflows: ["CI devops 2023 - Build and Push Docker Image"]
#     branches: [main]
#     types:
#       - completed
#comme,t

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: playbook
          key: ${{secrets.SSHKEYCENTOS}}
          inventory: |
            [all]
            ${{ secrets.DEPLOYHOST }}
          vault_password: ${{ secrets.VAULTPASSWORD }}
          options: |
            -u centos