name: CI devops 2023 - Test Backend

# Lorsqu'on push sur les branches main ou develop, déclenche ce workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # On récupère bien la dernière version du code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # On installe java sur la distribution correto
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      # On utilise Maven pour build et tester le code du Back-end, on utilise aussi sonar avec sonar Cloud en passant en paramètre nos informations.
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=RiSolJu_DevOpsClass -Dsonar.organization=risolju -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./Backend/pom.xml
